### ISSUE TITLE
feature: we can consider add a github action workflow automatic publish new docs each time we merge pr or commit something

### ISSUE THREAD

**Issue by yokofly** [timeplus-io/docs#200]
low priority for me.
i am not familiar with node
the npm/node/yarn version seems need either pin version or use latest one.
i use default ubuntu2004 apt source yarn not work.
then i switch to node official docker, and inside docker generate pdf works.

thoes things is really standard/normal, I think this can be done by github action.

**Comment by jovezhong** [comment]
it's already handled by netlify. When there is a new PR or pushed code, a doc site will be available.

**Comment by yokofly** [comment]
i need a offline PDF is this existed?

**Comment by jovezhong** [comment]
Generating the pdf is a bit more complicated, I don't recommend to generate it each time the code is changed.

The current pdf generation is based on the live site. So after the code is merged, netlify will take some time to build the live site, then the PDF tool will scan all pages then generate the PDF. The page->pdf will take 5-10mins, plus not all pages need to be in the PDF. Some customers doesn't care too much about the change log for our beta1/beta2, or cloud only content.  Plus every 100 commits/merge may only need a couple of PDF. So let's generate the PDF manually.

**Comment by yokofly** [comment]
that's looks fine to me, my current work routine is by yarn en-pdf-gen.
this is already our coded script, do you mean the covered docs probably also need update?
https://github.com/timeplus-io/docs/blob/main/pdf/docs.timeplus.com.txt

**Comment by jovezhong** [comment]
The docs.timeplus.com.txt is not the latest one.

Need to run `en-pdf-list` first to regenerate the full pages list based on the live site.
Then make judgement to skip some pages that customers may not want to see in the PDF. This is a tricky step, since there can be new docs page, no black list or white list.

I just updated the txt file
https://github.com/timeplus-io/docs/commit/94ed4a35e58eb7ae82ebab5762055c5de55af714

Now you can run `en-pdf-gen` task now. But if I add new docs page,  the PDF could be generated incorrectly.

**Comment by yokofly** [comment]
that's what i mean a workflow is more proper way to handle the inconsistency?

**Comment by jovezhong** [comment]
I see what you mean, @yokofly  A manual workflow is created to trigger the process. You can check the example at https://github.com/timeplus-io/docs/actions/runs/10257356443

This will first get all page list. Then use `grep` to exclude the "boring" pages from a blacklist, then use prince to generate the PDF and share it as a a build artifact.  You need to manually trigger it, since we don't want to generate a PDF whenever a code change is detected.

However those 2 page lists in the pdf folder can be out of date. I kept them as an easy way to generate PDF locally without github action
